#!/usr/bin/env bash

# This installs the program to a standardized system-wide path, so it can be used by anyone.
# Needs to be run with sudo

cp md2pdf /usr/local/bin/
chmod +x /usr/local/bin/md2pdf
mkdir -p /usr/local/share/md2pdf
cp mytemplate.html5 /usr/local/share/md2pdf/
cp mystyles.css /usr/local/share/md2pdf/
cp md2pdf.desktop /usr/share/applications

