#!/usr/bin/env bash

# This installs the program to a standardized Linux system-wide path.
# Needs to be run with sudo

cp md2pdf /usr/local/bin/
chmod +x /usr/local/bin/md2pdf
mkdir -p /usr/local/share/md2pdf
cp mytemplate.html5 /usr/local/share/md2pdf/
cp mystyles.css /usr/local/share/md2pdf/
cp md2pdf.desktop /usr/share/applications

#xdg-mime default md2pdf.desktop text/markdown

#update-mime-database $HOME/.local/share/mime
#update-mime-database

#update-desktop-database
#update-desktop-database $HOME/.local/share/applications
