#!/usr/bin/env bash

# https://github.com/skramm/md2pdf


function checkreq
{
	which $1 > /dev/null
	if [ $? != 0 ]
	then
		echo "ERROR: it seems you don't have $1 installed on your system, please install first"
		echo "with 'sudo apt install $1' (or whatever way you use to install stuff)."
		exit 1;
	fi
}

set +x
#echo "pwd=$(pwd)"
#echo "arg=$1"

if ! [ -n "$1" ]
then
	echo "md2dpf: you forgot to mention a filename"
	read
	exit 1
fi

if ! [ -e "$1" ]
then
	echo "md2dpf: file $1 is non-existent"
	read
	exit 2
fi

checkreq pandoc
checkreq wkhtmltopdf

# output logs are stored here:
mkdir -p /tmp/md2pdf

a=$1
# remove file extension
b=${a%.*}
#echo "b=$b"

ext=${a##*.}
#echo "ext=$ext"

# remove path
name=${b##*/}  
#echo "name=$name"

# path only (needed to get the images)
loc=${a%/*}
#echo "loc=$loc"

echo "md2pdf: converting file $a to $b.pdf"
pushd "$loc" >/dev/null

pandoc -V papersize=A4 \
	--standalone \
	--verbose \
	--template=/usr/local/share/md2pdf/mytemplate.html5 \
	--css=/usr/local/share/md2pdf/mystyles.css \
	--metadata pagetitle="$name" \
	--pdf-engine-opt=--enable-local-file-access \
	-V margin-left=0.7in \
	-V margin-right=0.7in \
	-V margin-top=0.7in \
	-V margin-bottom=0.7in \
	--from commonmark+autolink_bare_uris+pipe_tables \
	-t html \
	"$name.$ext" -o "$name.pdf" 1>"/tmp/md2pdf/md2pdf_$name.stdout" 2>"/tmp/md2pdf/md2pdf_$name.stderr"

err=$?
if [ $err != 0 ]
then
	echo -e "md2pdf: \e[31mFailure\e[0m, Pandoc returned $err instead of 0, something might gone wrong, check logs in /tmp/md2pdf"
	echo "Hit a key"
	read
else
	echo -e "md2pdf: \e[32mSuccess!\e[0m"
fi
popd >/dev/null

