#!/usr/bin/env bash

set +x

if ! [ -n "$1" ]
then
	echo "md2dpf: you forgot to mention a filename"
	exit 1
fi

if ! [ -e "$1" ]
then
	echo "md2dpf: file $1 is non-existent"
	exit 2
fi


a=$1
b=${a%.*}
echo "md2pdf: converting file $a to $b.pdf"

# in case of trouble, add this:
#	--verbose \
	
pandoc -V papersize=A4 \
	--metadata pagetitle="$a" \
	--data-dir=/usr/local/share/md2pdf \
	--template=mytemplate.html5 \
	-V margin-left=0.7in \
	-V margin-right=0.7in \
	-V margin-top=0.7in \
	-V margin-bottom=0.7in \
	-f markdown+autolink_bare_uris+pipe_tables \
	-t html $a -o $b.pdf
	

