# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mybuild:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pwd;uname -r;lsb_release -a

      - name: Test if able to write ouside !
        run: touch ../SECURITY_BREACH2.txt

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd
      - name: Install required stuff
        run: |
           sudo apt-get update
           sudo apt-get install pandoc
           sudo apt-get install wkhtmltopdf
      - name: Install
        run: sudo ./install
      - name: Run demo test
        run: md2pdf README.md


